config/routes.rb
Rails.application.routes.draw do
  resources :conditions
  resources :mychats
  devise_for :users

  root controller: :rooms, action: :index

  resources :room_messages
  resources :rooms
  get 'rooms/message'
  get 'moving_car' => "mychats#moving_car" 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/condition.rb
class Condition < ApplicationRecord
end

app/models/mychat.rb
class Mychat < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
	has_many :room_messages, dependent: :destroy,
                         inverse_of: :room
end

app/models/room_message.rb
class RoomMessage < ApplicationRecord
  belongs_to :user
  belongs_to :room, inverse_of: :room_messages
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
           # validates :username, uniqueness: true, presence: true
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected



  def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up) do |user_params|

  user_params.permit({ roles: [] }, :email, :password, :password_confirmation,:username,:image)

  end



  devise_parameter_sanitizer.permit(:account_update) do |user_params|

  user_params.permit({ roles: [] }, :email, :password, :password_confirmation, :current_password, :username, :image)

  end
  end

end

app/controllers/conditions_controller.rb
class ConditionsController < ApplicationController
  before_action :set_condition, only: [:show, :edit, :update, :destroy]

  # GET /conditions
  # GET /conditions.json
  def index
    @conditions = Condition.all
  end

  # GET /conditions/1
  # GET /conditions/1.json
  def show
  end

  # GET /conditions/new
  def new
    @condition = Condition.new
  end

  # GET /conditions/1/edit
  def edit
  end

  # POST /conditions
  # POST /conditions.json
  def create
    @condition = Condition.new(condition_params)

    respond_to do |format|
      if @condition.save
        format.html { redirect_to @condition, notice: 'Condition was successfully created.' }
        format.json { render :show, status: :created, location: @condition }
      else
        format.html { render :new }
        format.json { render json: @condition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conditions/1
  # PATCH/PUT /conditions/1.json
  def update
    respond_to do |format|
      if @condition.update(condition_params)
        format.html { redirect_to @condition, notice: 'Condition was successfully updated.' }
        format.json { render :show, status: :ok, location: @condition }
      else
        format.html { render :edit }
        format.json { render json: @condition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conditions/1
  # DELETE /conditions/1.json
  def destroy
    @condition.destroy
    respond_to do |format|
      format.html { redirect_to conditions_url, notice: 'Condition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_condition
      @condition = Condition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def condition_params
      params.require(:condition).permit(:text)
    end
end

app/controllers/mychats_controller.rb
class MychatsController < ApplicationController
  before_action :set_mychat, only: [:show, :edit, :update, :destroy]

  # GET /mychats
  # GET /mychats.json
  def index
    @mychats = Mychat.all
  end

  # GET /mychats/1
  # GET /mychats/1.json
  def show
  end

  # GET /mychats/new
  def new
    @mychat = Mychat.new
  end

  # GET /mychats/1/edit
  def edit
  end

  # POST /mychats
  # POST /mychats.json
  def create
    @mychat = Mychat.new(mychat_params)

    respond_to do |format|
      if @mychat.save
        format.html { redirect_to @mychat, notice: 'Mychat was successfully created.' }
        format.json { render :show, status: :created, location: @mychat }
      else
        format.html { render :new }
        format.json { render json: @mychat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mychats/1
  # PATCH/PUT /mychats/1.json
  def update
    respond_to do |format|
      if @mychat.update(mychat_params)
        format.html { redirect_to @mychat, notice: 'Mychat was successfully updated.' }
        format.json { render :show, status: :ok, location: @mychat }
      else
        format.html { render :edit }
        format.json { render json: @mychat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mychats/1
  # DELETE /mychats/1.json
  def destroy
    @mychat.destroy
    respond_to do |format|
      format.html { redirect_to mychats_url, notice: 'Mychat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mychat
      @mychat = Mychat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mychat_params
      params.require(:mychat).permit(:message, :username)
    end
end

app/controllers/room_messages_controller.rb
class RoomMessagesController < ApplicationController
before_action :load_entities

  def create
    @room_message = RoomMessage.create user: current_user,room: @room,message: params.dig(:room_message, :message)
       respond_to do |format|
      format.js {render inline: "location.reload();"}
    end 
  end

  protected

  def load_entities
    @room = Room.find params.dig(:room_message, :room_id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
	  before_action :load_entities

	def index
      @rooms = Room.all
	end
	def new
	    @room = Room.new
	end
	def show
		  @room_message = RoomMessage.new room: @room
		  @room_messages = @room.room_messages.includes(:user)
     end

   def create
    @room = Room.new permitted_parameters

    if @room.save
      flash[:success] = "Room #{@room.name} was created successfully"
      redirect_to rooms_path
    else
      render :new
    end
   end
   def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Deleted' }
      format.json { head :no_content }
    end
  end
  def edit
  end

  def update
    if @room.update_attributes(permitted_parameters)
      flash[:success] = "Room #{@room.name} was updated successfully"
      redirect_to rooms_path
    else
      render :new
    end
  end

  protected

  def load_entities
    @rooms = Room.all
    @room = Room.find(params[:id]) if params[:id]
  end

  def permitted_parameters
    params.require(:room).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_url(user)
  gravatar_id = Digest::MD5::hexdigest(user.email).downcase
  url = "https://gravatar.com/avatar/#{gravatar_id}.png"
end
end

app/helpers/conditions_helper.rb
module ConditionsHelper
end

app/helpers/mychats_helper.rb
module MychatsHelper
end

app/helpers/room_messages_helper.rb
module RoomMessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/conditions/_form.html.erb
<%= simple_form_for(@condition) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :text %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/conditions/edit.html.erb
<h1>Editing Condition</h1>

<%= render 'form', condition: @condition %>

<%= link_to 'Show', @condition %> |
<%= link_to 'Back', conditions_path %>

app/views/conditions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Term & Conditions</h1>

<center>
    <% @conditions.each do |condition| %> 
        <%= condition.text %><br>
    <% end %>
</center>
<br>
<%= link_to 'New Condition', new_condition_path %>

app/views/conditions/new.html.erb
<h1>New Condition</h1>

<%= render 'form', condition: @condition %>

<%= link_to 'Back', conditions_path %>

app/views/conditions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @condition.text %>
</p>

<%= link_to 'Edit', edit_condition_path(@condition) %> |
<%= link_to 'Back', conditions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Whatsaop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

      <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<header>
  <div class="container-fluid">
    <div class="jumbotron hero">
      <nav class="navbar">
        <div class="container">
          <div class="navbar-header">
            <div class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="glyphicon glyphicon-menu-hamburger"></span>
            </div>
                <% if current_user %>
    <div class="dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <img class="avatar" src="<%= current_user.image %>">
        <a class="navbar-brand" href="#"><strong> <%= current_user.username %></strong></a>
      </a>

      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
        <%= link_to 'Edit Profile',  edit_user_registration_path,class: 'dropdown-item' %>
      </div>
    </div>
  <% end %>
                </div>
             <!------------  <User Sign in Noticed and Login as> -->  
              <div id="navbar" class="collapse navbar-collapse navbar-bottom">
              
          
          </div>
          <div id="navbar" class="collapse navbar-collapse navbar-right">
            <ul class="nav navbar-nav">
              <li class="active"><a href="#">Home</a></li>
               <li><a href="/mychats">MyChats</a></li>
               <% if user_signed_in? %>
              <li><a href="/users/sign_out">Log Out</a></li>
              <%else%>
              <li><a href="/mychats">MyChats</a></li>
              <% end %>

            </ul>
      <hr class="hidden-sm hidden-md hidden-lg" style="margin: 0 30px;">
          </div><!--/.nav-collapse -->
        <marquee behavior="scroll" direction="left">This website is under maintenance.Due to this you can face some problems, Our team is solving the bugs and issues!
 :-)</marquee>
      </nav>
      <div class="text-center hero-row">
        <h1 class="heading"><span>My</span>Discord</h1>
                <h2 class="subheading">Discord Nitro 2.0</h2>
        <div class="btn-group">
          <a href="/conditions" button class="btn btn-lg btnx-blue" type="button">Read more T & C</a>
          <a href="/rooms" button class="btn btn-lg btnx-white"  type="button">Custom Chats</a>
          </div>
          <!-- ------------------<Form Tag in header> -------------->
       <% if notice %>
            <p class="alert alert-success"><%= notice %></p>
        <% end %>
                <% if alert %>
                  <p class="alert alert-d
                anger"><%= alert %></p>
                <% end %>
                    <%= yield %>
        
      </div>
      <div class="row header-features text-center hero-row hero-bottom">
        <div class="col-sm-6 col-md-4 col-lg-4">
          <span class="glyphicon glyphicon-pencil"></span>
          <div>
            <h3>Created By</h3>
            <p>Manish Singh<br>Sec-44, Noida,Uttar Pradesh<br>Contact: 9170002122</p>
          </div>
        </div>
        <div class="col-sm-6 col-md-4 col-lg-4">
          <span class="glyphicon glyphicon-cloud"></span>
          <div>
            <h3>History</h3>
            <p>The first online chat system was called Talkomatic, created by Doug Brown and David R. Woolley in 1973 on the PLATO System at the University of Illinoi</p>
          </div>
        </div>
        <div class="col-sm-6 col-md-4 col-lg-4">
          <span class="glyphicon glyphicon-link"></span>
          <div>
            <h3>About Us</h3>
            <p>Bittern Technologies is a leading full-service website and software development company headquartered in Noida, India. Serving clients large and small worldwide since 2015.</p>
             </div>
             </div>
        </div>
 
          
      </div>
   
  
</header>
<span class="blinking">Am I blinking?</span>

<script src="https://unpkg.com/scrollreveal/dist/scrollreveal.min.js"></script>

  </body>
</nav>
</div>

</html>
<style type="text/css">
@import url('https://fonts.googleapis.com/css?family=Open+Sans:400,700,800');
@import url('https://fonts.googleapis.com/css?family=Lato:400,700,900');

html, body {
  background-color: #fcfcfc;
  color: #131313;
  font-family: 'Open Sans', sans-serif;
  font-size: 14px;
}

h1, h2, h3, h4, h5, h6 {
  font-family: 'Lato', Comic Sans MS;
    font-weight: 700;
}

header, section, footer, aside, nav, main, article, figure {
    display: block; 
}
..blinking{
    animation:blinkingText 0.8s infinite;
}
@keyframes blinkingText{
    0%{     color: #000;    }
    49%{    color: transparent; }
    50%{    color: transparent; }
    99%{    color:transparent;  }
    100%{   color: #000;    }
}.blinking{
    animation:blinkingText 0.8s infinite;
}
@keyframes blinkingText{
    0%{     color: #000;    }
    49%{    color: transparent; }
    50%{    color: transparent; }
    99%{    color:transparent;  }
    100%{   color: #000;    }
}blinking{
    animation:blinkingText 0.8s infinite;
}
@keyframes blinkingText{
    0%{     color: #000;    }
    49%{    color: transparent; }
    50%{    color: transparent; }
    99%{    color:transparent;  }
    100%{   color: #000;    }
}ss
p {
  font-family: 'Open Sans', sans-serif;
  font-size: 14px;
}

.container-fluid {
  margin: 0;
  padding: 0;
}

.btnx-blue {
    background-color: #2874A6;
}
.btnx-red {
    background-color: #F25F70;
}
.btnx-white {
    background-color: #fcfcfc;
    color: #131313;
}

.navbar {
  background-color: transparent;
  border: 0;
  border-radius: 0;
}

.navbar-header > div > span {
  font-size: 32px;
  color: #fcfcfc;
}

.navbar-header > div > span:hover {
  cursor: pointer;
}

.navbar-brand {
  color: #fcfcfc;
  font-size: 24px;
}

.navbar-brand:hover,
.navbar-brand:focus {
  color: #2874A6;
  font-size: 24px;
}

.navbar-nav a {
  color: #fcfcfc;
  font-size: 14px;
}

.nav > li > a:hover,
.nav > li > a:focus {
  background-color: transparent;
  color: #2874A6;
}

.nav > li.active {
  border-bottom: 3px solid #2874A6;
}

.nav > hr {
    border: 2px solid #2874A6;
}

.jumbotron.hero {
  color: #000000;
  height: 100vh;
  margin: 0;
  padding: 0;
  background-image: url(https://images.wallpaperscraft.com/image/gradient_green_texture_131365_3840x2160.jpg);
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  display: table;
  border-radius: 0;
}

.jumbotron.hero .heading {
  font-weight: 900;
}

.jumbotron.hero .heading > span {
  color: #7410bd;
}

.jumbotron.hero .subheading {
  font-family: 'Open Sans', sans-serif;
    font-weight: 700;
  color: #000000;
}

.header-features {
  padding: 10px;
}

.header-features > div {
  padding: 0 50px;
}

.header-features > div > div {
  border-left: 1px solid #2874A6;
  border-right: 1px solid #2874A6;
}

.header-features > div > span {
  font-size: 32px;
}

.header-features p {
  font-size: 14px;
}

.hero-row {
  display: table-row;
}

.hero-row.hero-bottom {
  display: table-cell;
  vertical-align: bottom;
}

@media only screen and (max-width: 768px) {
  .navbar-nav a {
    font-size: 18px;
    text-align: center;
  }
  .nav > li.active {
    border-bottom: none;
  }
}
</style>
<script type="text/javascript">
  window.sr = ScrollReveal();
sr.reveal('.heading', {duration: 2000,
                       origin: 'left',
                       distance: '1000px'
                      });

sr.reveal('.subheading', {duration: 2000,
                          origin: 'right',
                          distance: '1000px'
                         });

sr.reveal('.btn-group', {duration: 2000,
                         origin: 'bottom',
                         distance: '100px'
                        });

sr.reveal('.navbar', {duration: 1000,
                      origin: 'top'
                     });

sr.reveal('.header-features', {duration: 3000,
                               origin: 'bottom'
                              });
</script>

app/views/mychats/_form.html.erb
<%= form_with(model: mychat, local: true) do |form| %>
  <% if mychat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mychat.errors.count, "error") %> prohibited this mychat from being saved:</h2>

      <ul>
      <% mychat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message,class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mychats/edit.html.erb
<h1>Editing Mychat</h1>

<%= render 'form', mychat: @mychat %>

<%= link_to 'Show', @mychat %> |
<%= link_to 'Back', mychats_path %>

app/views/mychats/index.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<p id="notice"><%= notice %></p>

<h1>Mychats</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Message</th>
      <th>Username</th>
      <th colspan=""></th>
    </tr>
  </thead>

  <tbody>
    <% @mychats.each do |mychat| %>
      <tr>
        <td><%= mychat.message %></td>
        <td><%= mychat.username %></td>
        <td><%= link_to 'Show', mychat,class: "wpcf7-form-control wpcf7-submit" %></td>
        <td><%= link_to 'Edit', edit_mychat_path(mychat),class: "wpcf7-form-control wpcf7-submit" %></td>
        <td><%= link_to 'Destroy', mychat, method: :delete, data: { confirm: 'Are you sure?' },class: "wpcf7-form-control wpcf7-submit" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mychat', new_mychat_path,class: "wpcf7-form-control wpcf7-submit" %>
<style type="text/css">
  .wpcf7-submit {
    background-image: linear-gradient(to right,#ff00cc 0%,#333399 51%,#ff00cc 100%);
    background-size: 200% auto;
    color: #ffffff !important;
    border-radius: 25px;
    font-weight: 400;
    font-size: 14px;
    text-transform: uppercase;
    border: none !important;
    transition: 0.7s all;
    -webkit-transition: 0.7s all;
    margin-top: 6px;
    padding-top: 10px;
    display: inline-block;
    width: 192px;
    height: 40px;
}
.wpcf7-submit:hover{
    background-position: right center;

}

</style>

app/views/mychats/moving_car.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Moving car in CSS</title>
	<h1>rtyuiop</h1>
	<link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
<div class="hero">
</div>
</body>
</html>
<style type="text/css">
	body{
	margin: 0;
	padding: 0;	
	}
.hero
{
	height: 100vh;
	width: 100%;
	background-image: url(sky.jpg);
	background-size: cover;
	background-position: center;
	position: relative;
	overflow-x: hidden;
}
</style>

app/views/mychats/new.html.erb
<h1>New Mychat</h1>

<%= render 'form', mychat: @mychat %>

<%= link_to 'Back', mychats_path %>

app/views/mychats/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-striped">
		<thead>
<tr>
  <th><strong>Message:</strong></th>
  <th><strong>Username:</strong></th>
</tr>
</thead>
<body>
<tr>
  <td><%= @mychat.message %></td>
  <td><%= @mychat.username %></td>
</tr>
</body>

<a href="/mychats/<%= @mychat.id%>/edit">
<td><%= link_to 'Edit', edit_mychat_path(@mychat),class: "gradient-button gradient-button-3" %></td>
<td><%= link_to 'Back', mychats_path,class: "gradient-button gradient-button-4"%></td>
</table>

<style type="text/css">
	.gradient-button {
    margin: 0px;
    font-family: "Arial Black", Gadget, sans-serif;
    font-size: 10px;
    padding: 9px;
    text-align: center;
    text-transform: uppercase;
    transition: 0.5s;
    background-size: 100% auto;
    color: #FFF;
    box-shadow: 0 0 20px #eee;
    border-radius: 10px;
    width: 100px;
    box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
    transition: all 0.3s cubic-bezier(.25,.8,.25,1);
    cursor: pointer;
    display: inline-block;
    border-radius: 35px;
}
.gradient-button:hover{
    box-shadow: 0 10px 20px rgba(0,0,0,0.19), 0 6px 6px rgba(0,0,0,0.23);
      margin: 8px 10px 12px;
}
.gradient-button-3 {background-image: linear-gradient(to right, #7474BF 0%, #348AC7 51%, #7474BF 100%)}
.gradient-button-3:hover { background-position: right center; 
}
.gradient-button-4 {background-image: linear-gradient(to right, #00d2ff 0%, #3a7bd5 51%, #00d2ff 100%)}
.gradient-button-4:hover { background-position: right center; }

</style>

app/views/rooms/_form.html.erb
<%= simple_form_for @room do |form| %>
  <%= form.input :name,class: "form-control"%>
  <%= form.submit "Save", class: 'btn btn-success' %>
<%end%>

app/views/rooms/_rooms.html.erb
<div class="mb-3">
  <%if current_user.role == "admin"%>
  <%= link_to new_room_path, class: 'btn btn-primary' do %>
    Create a room
  <% end %>
  <% end %>
</div>

<% if @rooms.present? %>
  <nav class="nav flex-column">
    <% @rooms.each do |room| %>
      <%= link_to room.name, room_path(room), class: 'nav-link room-nav-link' %>
       <%if current_user.role == "admin"%>
     <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" %></td>
     <% end %>
    <% end %>
  </nav>
<% else %>
  <div class="text-muted">
    The are no rooms
  </div>
<% end %>
<style type="text/css">
  .input-group .form-control {
    position: relative;
    z-index: 2;
    float: left;
    width: 64%;
    margin-bottom: 0;
}
  .room-nav-link {
    border: 1px solid #12b2e2 !important;
    background: #000000 !important; 
}
</style>

app/views/rooms/edit.html.erb
<h1>
  Editing room <%= @room.name %>
</h1>

<%= render partial: 'form' %>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col-12 col-md-3">
    <%= render partial: 'rooms' %>
  </div>

  <div class="col">
    <div class="alert alert-primary">
      <h4 class="alert-heading">
        Welcome to the Whatsuop!
      </h4>

      <p>
        We need to talk.
      </p>

      <hr />

      <p>
        Add in Custom Rooms to talk with Executive!.
      </p>
    </div>
  </div>
</div>
<style type="text/css">
  body {
    background-color:  linear-gradient(90deg,#257bf9,#2426ca);
  }
  .alert-primary {
    color: #000000;
    background-color: #0c82d624;
    border-color: #b8daff;
    width: 700px;
    height: 200px;
}
  
</style>

app/views/rooms/new.html.erb
<h1>
  New Custom room  
</h1>

<center><%= render partial: 'form' %></center>
<style type="text/css">
	#room_name{
    width: 400px;
    border-right-width: unset;
    background-color: transparent;
    color: white;
  }
</style>
<script type="text/javascript">
  $(document).ready(function() {            
    $('input').attr('required', true);   
  });
</script>

app/views/rooms/show.html.erb
<h1>
  <%= @room.name %>
</h1>

<div class="row">
  <div class="col-12 col-md-3">
    <%= render partial: 'rooms' %>
  </div>

  <div class="col">
    <div class="chat">
      <h2>Chats </h2>
      <% @room_messages.each do |room_message| %>
        <div class="chat-message-container">
          <div class="row no-gutters">
            <div class="col-auto text-center">
              <% if room_message.user.image.present? %>
              <%= image_tag room_message.user.image.url, class: "avatar" %>
              <% else %>
              <img src="<%= gravatar_url(room_message.user) %>" class="avatar" alt="">
              <% end %>
            </div>

            <div class="col">
              <div class="message-content">
                <p class="mb-1">
                  <%= room_message.message %>
                </p>

                <div class="text-right">
                  <small>
                    <%= room_message.user.username %>
                  </small>
                </div>
              </div><br>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <%= simple_form_for @room_message, remote: true do |form| %>
      <div class="input-group mb-3">
        <%= form.input :message, as: :string,
                                 wrapper: false,
                                 label: false,
                                 input_html: {
                                   class: 'chat-input', required: true
                                 } %>
        <div class="input-group-append">
          <%= form.submit "Send", class: 'btn btn-primary chat-input' %>
        </div>
      </div>

      <%= form.input :room_id, as: :hidden %>
    <% end %>
  </div>
</div>
<style type="text/css">
  .chat {
  background-color: transparent;
}
.message-content {
    padding: 5px !important;
    background: #D3D3D3 !important;
    width: 98% !important;
    border-bottom-left-radius: 10px;
    border-top-left-radius: 10px;
  }
  .text-right{
    background-color: #e082402e;
  }

.chat-input {
 border: px solid #000000;
  clear: both;
  overflow: hidden;
}
</style>
<script type="text/javascript">
  $(document).ready(function() {            
    $('input').attr('required', true);   
  });
</script>